import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Apple } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BackLink, FormaHeader } from "@/components/FormaMobile";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/auth")({ head: () => ({ meta: [{ title: "Sign In — Forma Studio" }, { name: "description", content: "Sign in or create your Forma Studio account." }, { property: "og:title", content: "Sign In — Forma Studio" }, { property: "og:description", content: "Access your designs and cloud library." }] }), component: AuthPage });
function AuthPage() {
  const navigate = useNavigate(); const [signup, setSignup] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function emailAuth() { setBusy(true); setError(""); const result = signup ? await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }) : await supabase.auth.signInWithPassword({ email, password }); setBusy(false); if (result.error) return setError(result.error.message); void navigate({ to: "/dashboard" }); }
  async function social(provider: "google" | "apple") { const result = await lovable.auth.signInWithOAuth(provider, { redirect_uri: `${window.location.origin}/dashboard` }); if (result.error) setError(result.error.message); }
  return <main className="min-h-screen bg-background"><FormaHeader /><section className="mx-auto max-w-md px-6 pb-16 pt-8"><BackLink to="/" label="Back to Home" /><p className="mt-12 text-[10px] font-bold uppercase tracking-[0.22em] text-primary">My account</p><h1 className="mt-3 text-4xl font-light">{signup ? "Create account" : "Welcome back"}</h1><p className="mt-3 text-sm text-muted-foreground">{signup ? "Save projects and continue from any device." : "Sign in to access your projects and cloud."}</p><div className="mt-8 space-y-3"><Button variant="outline" className="h-12 w-full" onClick={() => social("apple")}><Apple />Continue with Apple</Button><Button variant="outline" className="h-12 w-full" onClick={() => social("google")}>G&nbsp;&nbsp; Continue with Google</Button></div><div className="my-7 flex items-center gap-3 text-[10px] text-muted-foreground"><span className="h-px flex-1 bg-border" />OR<span className="h-px flex-1 bg-border" /></div><div className="space-y-4">{signup && <Input placeholder="Full name" value={name} onChange={(e) => setName(e.target.value)} className="h-12" />}<Input type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12" /><Input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-12" />{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<Button variant="studio" className="h-12 w-full" disabled={busy || !email || password.length < 6} onClick={emailAuth}>{busy ? "Please wait…" : signup ? "Create account" : "Sign in"}</Button></div><Button variant="link" className="mt-5 w-full text-xs" onClick={() => setSignup((value) => !value)}>{signup ? "Already have an account? Sign in" : "Don't have an account? Sign up"}</Button></section></main>;
}