import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BackLink, FormaHeader } from "@/components/FormaMobile";
import { supabase } from "@/integrations/supabase/client";
import { getGuestCredits, GUEST_CREDITS_KEY, GUEST_PHOTO_CHAT_KEY } from "@/lib/guest-trial";
import type { UIMessage } from "ai";

export const Route = createFileRoute("/auth")({ head: () => ({ meta: [{ title: "Sign In — FormAI STUDIO" }, { name: "description", content: "Sign in or create your FormAI STUDIO account." }, { property: "og:title", content: "Sign In — FormAI STUDIO" }, { property: "og:description", content: "Access your designs and cloud library." }] }), component: AuthPage });
function AuthPage() {
  const navigate = useNavigate(); const [signup, setSignup] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function emailAuth() { setBusy(true); setError(""); const cleanEmail = email.trim().toLowerCase(); const result = signup ? await supabase.auth.signUp({ email: cleanEmail, password, options: { data: { full_name: name.trim() } } }) : await supabase.auth.signInWithPassword({ email: cleanEmail, password }); if (result.error || !result.data.user) { setBusy(false); return setError(result.error?.message ?? "Sign in failed."); } if (result.data.session) await supabase.rpc("activate_vip_access"); const userId = result.data.user.id; const remaining = getGuestCredits(); await supabase.from("guest_credit_claims").insert({ user_id: userId, remaining_credits: remaining }).then(() => undefined); const savedChat = window.localStorage.getItem(GUEST_PHOTO_CHAT_KEY); if (savedChat) { const messages = JSON.parse(savedChat) as UIMessage[]; const rows = messages.map((message) => ({ user_id: userId, role: message.role, content: message.parts.map((part) => part.type === "text" ? part.text : "").join("") })).filter((message) => (message.role === "user" || message.role === "assistant") && message.content); if (rows.length) await supabase.from("photo_ai_messages").insert(rows); window.localStorage.removeItem(GUEST_PHOTO_CHAT_KEY); } window.localStorage.removeItem(GUEST_CREDITS_KEY); setBusy(false); void navigate({ to: "/dashboard", replace: true }); }
  return <main className="min-h-screen bg-background"><FormaHeader /><section className="mx-auto max-w-md px-6 pb-16 pt-8"><BackLink to="/" label="Back to Home" /><p className="mt-12 text-[10px] font-bold uppercase tracking-[0.22em] text-primary">My account</p><h1 className="mt-3 text-4xl font-light">{signup ? "Create account" : "Welcome back"}</h1><p className="mt-3 text-sm text-muted-foreground">{signup ? "Create your account instantly. No email verification needed." : "Sign in to open your private dashboard."}</p><div className="mt-8 space-y-4">{signup && <Input placeholder="Full name" maxLength={100} value={name} onChange={(e) => setName(e.target.value)} className="h-12" />}<Input type="email" autoComplete="email" maxLength={255} placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} className="h-12" /><Input type="password" autoComplete={signup ? "new-password" : "current-password"} minLength={8} maxLength={72} placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-12" />{signup && <p className="text-xs text-muted-foreground">Use at least 8 characters.</p>}{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<Button variant="studio" className="h-12 w-full" disabled={busy || !email.includes("@") || password.length < 8} onClick={emailAuth}>{busy ? "Please wait…" : signup ? "Create account" : "Sign in"}</Button></div><Button variant="link" className="mt-5 w-full text-xs" onClick={() => { setSignup((value) => !value); setError(""); }}>{signup ? "Already have an account? Sign in" : "New here? Create an account"}</Button></section></main>;
}