import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {revenueCatEvent,stripeBillingEvent} from '../src/lib/billing-events.ts';
const user='11111111-1111-4111-8111-111111111111';
const future=Date.now()+86400000;
const rc={id:'event1',type:'INITIAL_PURCHASE',app_user_id:user,product_id:'app.formaistudio.formai.pro_monthly',original_transaction_id:'original1',transaction_id:'tx1',environment:'SANDBOX',event_timestamp_ms:Date.now(),expiration_at_ms:future};
assert.equal(revenueCatEvent(rc)?.amount,2000);
assert.equal(revenueCatEvent({...rc,type:'CANCELLATION'})?.active,true);
assert.equal(revenueCatEvent({...rc,type:'CANCELLATION'})?.amount,0);
assert.equal(revenueCatEvent({...rc,type:'EXPIRATION'})?.active,false);
assert.throws(()=>revenueCatEvent({...rc,environment:'BAD'}));
assert.throws(()=>revenueCatEvent({...rc,app_user_id:'$RCAnonymousID:unverified'}));
const sub={id:'sub1',metadata:{userId:user},status:'active',items:{data:[{price:{lookup_key:'pro_monthly'},current_period_end:future/1000}]}};
const invoice={id:'in1',paid:true,billing_reason:'subscription_cycle'};
const evt={id:'evt1',livemode:false,type:'invoice.paid',created:Date.now()/1000,data:{object:invoice}};
assert.equal(stripeBillingEvent(evt,sub,'sandbox').grantId,'in1');
assert.equal(stripeBillingEvent({...evt,type:'customer.subscription.created'},sub,'sandbox').amount,0);
assert.throws(()=>stripeBillingEvent(evt,sub,'live'));
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select null::uuid$$;insert into auth.users values('${user}');`);
await db.exec(await readFile(new URL('../supabase/migrations/20260917190000_billing_ledger.sql',import.meta.url),'utf8'));
const grant=async(event:string,grantId='invoice1',at='2026-09-17T10:00:00Z',active=true)=>db.query(`select public.apply_billing_event('stripe','sandbox',$1,$2,'subscription1','pro_monthly',$3,'2099-01-01',$4,$5,2)`,[event,user,active,at,grantId]);
await grant('e1');await grant('e1');await grant('e2');
const balance=async()=>Number((await db.query<any>('select balance from billing_wallets')).rows[0].balance);
assert.equal(await balance(),2,'duplicate event and duplicate invoice cannot double fund');
const reserve=async(id:string,hash='hash',env='sandbox')=>(await db.query<any>('select public.reserve_generation($1,$2,$3,\'stripe\',$4,1) as status',[user,id,env,hash])).rows[0].status;
const ids=['22222222-2222-4222-8222-222222222221','22222222-2222-4222-8222-222222222222','22222222-2222-4222-8222-222222222223'];
assert.equal(await reserve(ids[0],'hash','live'),'subscription_required');
assert.equal(await reserve(ids[0]),'accepted');assert.equal(await reserve(ids[0]),'reserved');
await assert.rejects(()=>reserve(ids[0],'different'));
const results=await Promise.all([reserve(ids[1]),reserve(ids[2])]);
assert.deepEqual(results.sort(),['accepted','busy']);assert.equal(await balance(),0);
await db.query('select public.finish_generation($1,$2,\'refunded\')',[user,ids[0]]);
await db.query('select public.finish_generation($1,$2,\'refunded\')',[user,ids[0]]);assert.equal(await balance(),1,'refund once');
await grant('e3','invoice1','2026-09-17T11:00:00Z',false);
await grant('e4','invoice1','2026-09-17T09:00:00Z',true);
assert.equal((await db.query<any>('select active from billing_entitlements')).rows[0].active,false,'old event must not revive access');
await db.query("select public.finish_generation($1,$2,'completed')",[user,ids[1]]);
await db.query("select public.ensure_trial_wallet($1,'sandbox')",[user]);
await db.query("select public.ensure_trial_wallet($1,'sandbox')",[user]);
assert.equal((await db.query<any>("select balance from billing_wallets where provider='trial'")).rows[0].balance,4,'trial is seeded once');
await db.query("insert into generation_operations select $1, md5(i::text)::uuid,'sandbox','trial','test',0,'completed',now(),now() from generate_series(1,1000) i",[user]);
assert.equal(await reserve(ids[2]),'daily_limit','global circuit breaker precedes provider calls');
await db.exec('set role authenticated');
await assert.rejects(()=>db.query('update billing_wallets set balance=999'));
await assert.rejects(()=>db.query('select public.finish_generation($1,$2,\'completed\')',[user,ids[0]]));
await db.close();
console.log('PASS billing: real PostgreSQL transactions, duplicate invoice/event, atomic spend, duplicate refund, stale events, sandbox isolation and RPC privileges; cancellation keeps paid term.');
