import { createFileRoute } from "@tanstack/react-router";
import { convertToModelMessages, streamText, type UIMessage } from "ai";

export const Route = createFileRoute("/api/photo-chat")({
  server: { handlers: { POST: async ({ request }) => {
    const contentLength = Number(request.headers.get("content-length") ?? 0);
    if (contentLength > 15 * 1024 * 1024) return new Response("Image is too large", { status: 413 });
    const body = await request.json().catch(() => null) as { messages?: unknown; contextStart?: number; currentImage?: string | null } | null;
    if (!body || !Array.isArray(body.messages) || body.messages.length > 100) return new Response("Messages are required", { status: 400 });
    const start = Number.isInteger(body.contextStart) && body.contextStart! >= 0 ? Math.min(body.contextStart!, body.messages.length) : 0;
    const recent = (body.messages as UIMessage[]).slice(start).slice(-6).map(m=>({...m,parts:m.parts.filter(p=>p.type !== "file")}));
    if (body.currentImage) {
      if (typeof body.currentImage !== "string" || body.currentImage.length > 3_800_000 || !/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(body.currentImage)) return new Response("Invalid current image",{status:400});
      const last = [...recent].reverse().find(m=>m.role==="user");
      if (last) (last.parts as UIMessage["parts"]).push({type:"file",mediaType:body.currentImage.slice(5,body.currentImage.indexOf(";")),url:body.currentImage});
    }
    const key = process.env.OPENAI_API_KEY;
    if (!key) return new Response("Photo AI is unavailable.", { status: 500 });
    const { createOpenAIChatModel } = await import("@/lib/openai-chat.server");
    const result = streamText({
      maxRetries: 0,
      model: createOpenAIChatModel(key),
          maxOutputTokens: 2048,
          abortSignal: request.signal,
      system: "You are Photo AI, a concise expert interior design and image-editing assistant. The latest user request overrides conflicting older instructions. Use only relevant recent context. The most recent attached image is the current scene. Never reintroduce canceled changes. Ask 1-3 short clarifying questions when the target object, scope or requested change is ambiguous; do not invent user preferences. Never claim an image was generated by this chat. Analyze the current attached room or object image. Help users add, remove, replace and edit objects, materials, finishes, context and illumination while preserving perspective. When a user asks for a visual change, respond with a precise production-ready image-edit instruction and briefly explain what will be preserved. If no image is attached, rely only on the user's description.",
      messages: await convertToModelMessages(recent),
    });
    return result.toUIMessageStreamResponse({ originalMessages: body.messages as UIMessage[], onError: () => "The studio assistant is momentarily unavailable. Please try again in a bit." });
  } } },
});
