import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Box, FileImage, FolderOpen } from "lucide-react";
import { BackLink, FormaHeader, PageIntro, ToolTabBar } from "@/components/FormaMobile";
import { listProjects } from "@/lib/projects.functions";
export const Route = createFileRoute("/_authenticated/cloud")({ head: () => ({ meta: [{ title: "My Cloud — FormAI STUDIO" }, { name: "description", content: "Your saved AI designs, products and materials." }, { property: "og:title", content: "My Cloud" }, { property: "og:description", content: "Access saved designs and creative assets." }] }), component: CloudPage });
function CloudPage() {
  const fetchProjects = useServerFn(listProjects);
  const { data: projects = [], isLoading } = useQuery({ queryKey: ["cloud-projects"], queryFn: () => fetchProjects() });
  return <main className="min-h-screen bg-background"><FormaHeader /><div className="px-5 pt-7"><BackLink /></div><PageIntro eyebrow="Personal library" title="My Cloud" description="Your saved projects, generated images, product references and materials appear here." /><section className="px-5 pb-[calc(6rem+env(safe-area-inset-bottom))]"><div className="grid grid-cols-3 gap-2">{[[FolderOpen,"Projects"],[FileImage,"Outputs"],[Box,"Products"]].map(([Icon,label]) => { const ItemIcon = Icon as typeof Box; return <div key={label as string} className="flex min-h-28 flex-col items-center justify-center gap-3 bg-secondary text-xs"><ItemIcon className="size-5" />{label as string}</div>; })}</div>{isLoading && <p className="mt-12 text-center text-sm text-muted-foreground">Loading your cloud…</p>}{!isLoading && projects.length === 0 && <div className="mt-12 text-center"><p className="text-lg font-light">Your cloud is empty</p><p className="mt-2 text-xs text-muted-foreground">Create your first design to see it here.</p></div>}{projects.length > 0 && <div className="mt-8 grid grid-cols-2 gap-3">{projects.map((project) => <article key={project.id} className="overflow-hidden rounded-2xl border border-border bg-secondary">{project.render_image_url ? <img src={project.render_image_url} alt={project.name} className="aspect-square w-full object-cover" /> : <div className="grid aspect-square place-items-center"><FolderOpen /></div>}<div className="p-3"><h2 className="text-sm">{project.name}</h2><p className="mt-1 text-[10px] text-muted-foreground">{new Date(project.updated_at).toLocaleDateString()}</p></div></article>)}</div>}</section><ToolTabBar /></main>;
}