import { useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useRef, useState, type ChangeEvent } from "react";
import { Download, ImagePlus, Lamp, LoaderCircle, MapPin, RotateCcw, SlidersHorizontal, Sparkles, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { BackLink, FormaHeader, PageIntro, ToolTabBar } from "@/components/FormaMobile";
import { ToolInformation, type ToolInfoSection } from "@/components/ToolInformation";
import { streamImage } from "@/lib/stream-image";
import { useCredits } from "@/hooks/use-credits";
import { colorPalettes, designStyles, finishOptions, materialOptions, useOptions, vegetationOptions, wallArtOptions } from "@/lib/studio-options";
import { saveProject } from "@/lib/projects.functions";
import { FurnitureLibraryPicker } from "@/components/FurnitureLibraryPicker";
import { SceneComposer } from "@/components/SceneComposer";
import { AiPlanGenerator } from "@/components/AiPlanGenerator";

export function ImageStudio({ eyebrow, title, description, suggestions, information, planMode = false, enableComposer = false }: { eyebrow: string; title: string; description: string; suggestions: string[]; information?: ToolInfoSection[]; planMode?: boolean; enableComposer?: boolean }) {
  const fileRef = useRef<HTMLInputElement>(null); const referenceRef = useRef<HTMLInputElement>(null); const [source, setSource] = useState<string | null>(null); const [references, setReferences] = useState<string[]>([]); const [fileName, setFileName] = useState(""); const [unit, setUnit] = useState<"meters" | "feet">("meters"); const [environment, setEnvironment] = useState<"indoor" | "outdoor">("indoor"); const [roomPurpose, setRoomPurpose] = useState("Living room"); const [width, setWidth] = useState("4"); const [length, setLength] = useState("5"); const [height, setHeight] = useState("2.7"); const [style, setStyle] = useState("Contemporary"); const [palette, setPalette] = useState("Warm neutrals"); const [materials, setMaterials] = useState<string[]>([]); const [finishes, setFinishes] = useState<string[]>([]); const [spaceUse, setSpaceUse] = useState("Relaxation & entertainment"); const [vegetation, setVegetation] = useState("None"); const [wallArt, setWallArt] = useState("No artwork"); const [budget, setBudget] = useState("50000"); const [location, setLocation] = useState(""); const [time, setTime] = useState("Golden hour"); const [lighting, setLighting] = useState("Soft diffused"); const [tone, setTone] = useState("Warm realistic"); const [exposure, setExposure] = useState(0); const [brightness, setBrightness] = useState(0); const [contrast, setContrast] = useState(0); const [saturation, setSaturation] = useState(0); const [warmth, setWarmth] = useState(10); const [result, setResult] = useState<string | null>(null); const [prompt, setPrompt] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const { credits, signedIn, vip, consume } = useCredits();
  const navigate = useNavigate();
  const saveStudioProject = useServerFn(saveProject);
  function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10_000_000) return setError("Use a file smaller than 10 MB."); setError(""); setFileName(file.name); if (file.type === "application/pdf") { setSource(null); setResult(null); return; } const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === "string") { setSource(reader.result); setResult(null); } }; reader.readAsDataURL(file); }
  function uploadReferences(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []).slice(0, 4); if (files.some((file) => file.size > 10_000_000)) return setError("Each reference must be smaller than 10 MB."); Promise.all(files.map((file) => new Promise<string>((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : ""); reader.readAsDataURL(file); }))).then((images) => setReferences(images.filter(Boolean))); }
  async function generate() { if ((!planMode && !source) || (planMode && (!width || !length || !height))) return; setBusy(true); setError(""); if (!(await consume())) { setBusy(false); if (!signedIn) { void navigate({ to: "/auth" }); return; } setError("You have no credits left. Open your Wallet to continue."); return; } const grading = enableComposer ? `Editorial controls: tone ${tone}; exposure ${exposure > 0 ? "+" : ""}${exposure}; brightness ${brightness > 0 ? "+" : ""}${brightness}; contrast ${contrast > 0 ? "+" : ""}${contrast}; saturation ${saturation > 0 ? "+" : ""}${saturation}; warmth ${warmth > 0 ? "+" : ""}${warmth}. Apply these as restrained professional photographic corrections while keeping all colors and materials realistic.` : ""; const configuration = planMode ? `${environment} ${roomPurpose}, ${width} × ${length} × ${height} ${unit}. ${style} style. ${palette} palette. Architectural materials: ${materials.join(", ") || "designer selected"}. Finishes: ${finishes.join(", ") || "designer selected"}. Primary use: ${spaceUse}. Vegetation: ${vegetation}. Wall art: ${wallArt}. Furniture budget: ${budget || "not specified"}. ${prompt}` : `${prompt}. Location/context: ${location || "preserve original"}. Time: ${time}. Lighting: ${lighting}. ${grading}`; let finalImage: string | null = null; try { await streamImage(`${configuration}. ${references.length ? "MANDATORY EXACT FURNITURE FIDELITY: treat every additional reference image as the definitive product specification. Reproduce each referenced furniture piece without redesign, substitution or stylistic reinterpretation. Match 100% of the visible silhouette, proportions, dimensions, construction details, seams, edges, legs, hardware, material type, grain, weave, finish, color and surface texture. Only adapt camera perspective, scale, occlusion, illumination and contact shadows so the exact piece sits naturally in the room." : "Do not invent named furniture brands or branded products."} Refined luxury editorial interior photograph with physically realistic material response, no text, no logos.`, source, (image, isFinal) => { setResult(image); if (isFinal) finalImage = image; }, references); if (signedIn && finalImage) await saveStudioProject({ data: { name: `${roomPurpose} · ${style}`, mode: "render", prompt: configuration, renderImageUrl: finalImage, sourceImageUrl: null, settings: { unit, environment, roomPurpose, width, length, height, style, palette, materials: materials.join(", "), finishes: finishes.join(", "), spaceUse, vegetation, wallArt, budget } } }); } catch (cause) { setError(cause instanceof Error ? cause.message : "The design could not be generated."); } finally { setBusy(false); } }
  function download() { if (!result) return; const link = document.createElement("a"); link.href = result; link.download = "formai-studio-ai-design.png"; link.click(); }
  const roomOptions = environment === "indoor" ? ["Living room", "Dining room", "Bedroom", "Lounge", "Kitchen", "Home office", "Bathroom", "Restaurant", "Bar", "Retail space", "Reception", "Conference room", "Open plan office", "Lobby"] : ["Terrace", "Patio", "Garden", "Pool area", "Outdoor dining", "Outdoor lounge", "Balcony"];
  const toggle = (value: string, values: string[], setter: (next: string[]) => void) => setter(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  const pills = (options: readonly string[], value: string, setter: (next: string) => void) => <div className="mt-3 flex flex-wrap gap-2">{options.map((option) => <Button key={option} type="button" size="sm" variant={value === option ? "default" : "outline"} onClick={() => setter(option)}>{option}</Button>)}</div>;
  const multiPills = (options: readonly string[], values: string[], setter: (next: string[]) => void) => <div className="mt-3 flex flex-wrap gap-2">{options.map((option) => <Button key={option} type="button" size="sm" variant={values.includes(option) ? "default" : "outline"} onClick={() => toggle(option, values, setter)}>{option}</Button>)}</div>;
  const ready = planMode ? Boolean(width && length && height) : Boolean(source && prompt.trim().length >= 6);
  return <main className="min-h-screen bg-background"><FormaHeader /><div className="px-5 pt-7"><BackLink /></div><PageIntro eyebrow={eyebrow} title={title} description={description}><p className="mt-4 text-xs font-bold uppercase tracking-[0.14em]">{vip ? "VIP · Unlimited" : `${credits} ${signedIn ? "account" : "guest"} credits left`}</p></PageIntro><section className="px-5 pb-[calc(6rem+env(safe-area-inset-bottom))]">
    {planMode && <div className="mb-5"><p className="text-[10px] font-bold uppercase tracking-[0.2em]">01 · Upload your plan</p><p className="mt-2 text-xs text-muted-foreground">Optional · PDF, JPG or PNG · one room or space</p></div>}
    <input ref={fileRef} type="file" accept={planMode ? "application/pdf,image/png,image/jpeg" : "image/png,image/jpeg,image/webp"} className="sr-only" onChange={upload} />
    <input ref={referenceRef} type="file" multiple accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={uploadReferences} />
    <Button type="button" variant="outline" onClick={() => fileRef.current?.click()} className="relative min-h-56 w-full overflow-hidden rounded-2xl p-0">{source ? <img src={result ?? source} alt={result ? "AI-designed interior result" : "Uploaded interior"} className={`h-72 w-full object-cover ${busy ? "blur-md" : ""}`} /> : <span className="px-6 text-center"><Upload className="mx-auto size-6" /><span className="mt-3 block text-sm font-bold">{fileName || (planMode ? "Upload your plan" : "Upload your space")}</span><span className="mt-1 block text-xs text-muted-foreground">{planMode ? "PDF, JPG or PNG · Optional" : "JPG, PNG or WEBP"}</span></span>}{busy && <span className="absolute inset-0 grid place-items-center bg-foreground/25 text-primary-foreground"><LoaderCircle className="animate-spin" /></span>}</Button>
    {fileName && <Button type="button" variant="ghost" size="sm" className="mt-2" onClick={() => { setFileName(""); setSource(null); setResult(null); if (fileRef.current) fileRef.current.value = ""; }}><X />Remove plan</Button>}
    {enableComposer && source && <div className="mt-6"><SceneComposer sourceImage={result ?? source} signedIn={signedIn} onUseComposition={(image, instruction, texture) => { setSource(image); setResult(null); setPrompt(instruction); if (texture) setReferences((current) => [...current.filter((item) => item !== texture), texture].slice(-5)); }} /></div>}
    {planMode && <>
      <div className="organic-divider py-8"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em]">02 · Overall dimensions</p><p className="mt-2 text-xs text-muted-foreground">Enter the room measurements manually</p></div><div className="flex rounded-xl border border-foreground p-1"><Button type="button" size="sm" variant={unit === "feet" ? "default" : "ghost"} onClick={() => setUnit("feet")}>Feet</Button><Button type="button" size="sm" variant={unit === "meters" ? "default" : "ghost"} onClick={() => setUnit("meters")}>Meters</Button></div></div><div className="mt-5 grid grid-cols-3 gap-3"><label className="text-xs">Width<Input value={width} onChange={(event) => setWidth(event.target.value)} type="number" min="0.1" step="0.1" inputMode="decimal" className="mt-2 h-12" /></label><label className="text-xs">Length<Input value={length} onChange={(event) => setLength(event.target.value)} type="number" min="0.1" step="0.1" inputMode="decimal" className="mt-2 h-12" /></label><label className="text-xs">Height<Input value={height} onChange={(event) => setHeight(event.target.value)} type="number" min="0.1" step="0.1" inputMode="decimal" className="mt-2 h-12" /></label></div></div>
      <div className="organic-divider py-8"><p className="text-[10px] font-bold uppercase tracking-[0.2em]">03 · Room purpose</p><div className="mt-5 grid grid-cols-2 gap-3"><Button type="button" variant={environment === "indoor" ? "default" : "outline"} onClick={() => { setEnvironment("indoor"); setRoomPurpose("Living room"); }}>Indoor</Button><Button type="button" variant={environment === "outdoor" ? "default" : "outline"} onClick={() => { setEnvironment("outdoor"); setRoomPurpose("Terrace"); }}>Outdoor</Button></div>{pills(roomOptions, roomPurpose, setRoomPurpose)}</div>
      <div className="organic-divider py-8"><p className="text-[10px] font-bold uppercase tracking-[0.2em]">04 · Design direction</p><p className="mt-5 text-xs uppercase tracking-[0.14em]">Design style</p>{pills(designStyles, style, setStyle)}<p className="mt-6 text-xs uppercase tracking-[0.14em]">Color palette</p>{pills(colorPalettes, palette, setPalette)}<p className="mt-6 text-xs uppercase tracking-[0.14em]">New materials</p>{multiPills(materialOptions, materials, setMaterials)}<p className="mt-6 text-xs uppercase tracking-[0.14em]">Finishes to include</p>{multiPills(finishOptions, finishes, setFinishes)}</div>
      <div className="organic-divider py-8"><p className="text-[10px] font-bold uppercase tracking-[0.2em]">05 · Living details</p><p className="mt-5 text-xs uppercase tracking-[0.14em]">Primary use</p>{pills(useOptions, spaceUse, setSpaceUse)}<p className="mt-6 text-xs uppercase tracking-[0.14em]">Vegetation</p>{pills(vegetationOptions, vegetation, setVegetation)}<p className="mt-6 text-xs uppercase tracking-[0.14em]">Wall art</p>{pills(wallArtOptions, wallArt, setWallArt)}<label className="mt-6 block text-xs uppercase tracking-[0.14em]">Furniture budget<Input value={budget} onChange={(event) => setBudget(event.target.value)} type="number" min="0" step="1000" inputMode="numeric" className="mt-2 h-12" /></label></div>
    </>}
    {(source || planMode) && <div className="mt-6 space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{suggestions.map((item) => <Button key={item} variant="secondary" size="sm" className="shrink-0" onClick={() => setPrompt(item)}>{item}</Button>)}</div><Textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder={planMode ? "Add any special requirements or furniture preferences…" : "Chat with AI: add, remove, replace or transform anything…"} className="min-h-28 resize-none" />
      <Button type="button" variant="outline" className="h-11 w-full" onClick={() => referenceRef.current?.click()}><ImagePlus />{references.length ? `${references.length} exact furniture reference${references.length > 1 ? "s" : ""} attached` : "Upload exact furniture references"}</Button>
      <FurnitureLibraryPicker signedIn={signedIn} selected={references} onToggle={(imageUrl) => setReferences((current) => current.includes(imageUrl) ? current.filter((item) => item !== imageUrl) : current.length < 5 ? [...current, imageUrl] : current)} />
      {references.length > 0 && <div className="grid grid-cols-4 gap-2">{references.map((reference, index) => <div key={`${reference.slice(-24)}-${index}`} className="relative aspect-square overflow-hidden rounded-xl border border-border"><img src={reference} alt={`Object reference ${index + 1}`} className="h-full w-full object-cover" /><Button type="button" variant="default" size="icon" aria-label={`Remove reference ${index + 1}`} className="absolute right-1 top-1 size-7 min-h-0 rounded-full" onClick={() => setReferences((current) => current.filter((_, itemIndex) => itemIndex !== index))}><X className="size-3" /></Button></div>)}</div>}
      {!planMode && <div className="grid grid-cols-2 gap-3"><label className="text-xs"><span className="flex items-center gap-1"><MapPin className="size-3" />Location/context</span><Input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Paris, desert, coast…" className="mt-2 h-11" /></label><label className="text-xs"><span className="flex items-center gap-1"><Lamp className="size-3" />Time & light</span><select value={time} onChange={(event) => setTime(event.target.value)} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 text-xs"><option>Sunrise</option><option>Daytime</option><option>Golden hour</option><option>Sunset</option><option>Blue hour</option><option>Night</option></select></label></div>}
      {!planMode && <div><p className="text-xs uppercase tracking-[0.14em]">Lighting style</p>{pills(["Natural daylight", "Soft diffused", "Warm ambient", "Dramatic", "Studio editorial"], lighting, setLighting)}</div>}
      {enableComposer && <div className="space-y-5 border-y border-border py-6"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.14em]"><SlidersHorizontal className="size-4" />Editorial image controls</p><p className="mt-2 text-xs text-muted-foreground">Fine-tune realistic photographic grading before rendering.</p></div><div><p className="text-xs uppercase tracking-[0.14em]">Tone</p>{pills(["Warm realistic", "Neutral daylight", "Soft editorial", "Rich evening"], tone, setTone)}</div>{[["Exposure", exposure, setExposure], ["Brightness", brightness, setBrightness], ["Contrast", contrast, setContrast], ["Saturation", saturation, setSaturation], ["Warmth", warmth, setWarmth]].map(([label, value, setter]) => <label key={label as string} className="block text-xs"><span className="flex justify-between"><span>{label as string}</span><span>{Number(value) > 0 ? "+" : ""}{value as number}</span></span><input type="range" min="-50" max="50" step="1" value={value as number} onChange={(event) => (setter as (next: number) => void)(Number(event.target.value))} className="mt-2 h-11 w-full accent-foreground" /></label>)}</div>}
      {error && <p role="alert" className="text-xs text-destructive">{error}</p>}<Button variant="studio" className="h-12 w-full" disabled={busy || !ready} onClick={generate}>{busy ? <LoaderCircle className="animate-spin" /> : <Sparkles />}{busy ? "Creating proposal…" : planMode ? "Generate proposal · 1 credit" : "Apply AI design · 1 credit"}</Button>{result && <AiPlanGenerator sourceImage={result} kind="space" />}<div className="grid grid-cols-2 gap-3"><Button variant="outline" onClick={() => { setSource(null); setReferences([]); setFileName(""); setResult(null); setPrompt(""); }}><RotateCcw />Reset</Button><Button variant="outline" disabled={!result} onClick={download}><Download />Download</Button></div></div>}
    {!source && !planMode && <Button variant="outline" className="mt-4 h-11 w-full" onClick={() => fileRef.current?.click()}><ImagePlus />Select a photo</Button>}{error && !source && !planMode && <p role="alert" className="mt-3 text-xs text-destructive">{error}</p>}{information && <ToolInformation sections={information} />}
  </section><ToolTabBar /></main>;
}