import { useRef, useState, type ChangeEvent } from "react";
import { Download, ImagePlus, LoaderCircle, RotateCcw, Sparkles, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { BackLink, FormaHeader, PageIntro } from "@/components/FormaMobile";
import { streamImage } from "@/lib/stream-image";

export function ImageStudio({ eyebrow, title, description, suggestions }: { eyebrow: string; title: string; description: string; suggestions: string[] }) {
  const fileRef = useRef<HTMLInputElement>(null); const [source, setSource] = useState<string | null>(null); const [result, setResult] = useState<string | null>(null); const [prompt, setPrompt] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 6_000_000) return setError("Use an image smaller than 6 MB."); const reader = new FileReader(); reader.onload = () => { if (typeof reader.result === "string") { setSource(reader.result); setResult(null); } }; reader.readAsDataURL(file); }
  async function generate() { if (!source || prompt.trim().length < 6) return; setBusy(true); setError(""); try { await streamImage(`${prompt}. Refined high-end interior visualization, coherent perspective, realistic materials, no text, no logos.`, source, (image) => setResult(image)); } catch (cause) { setError(cause instanceof Error ? cause.message : "The design could not be generated."); } finally { setBusy(false); } }
  function download() { if (!result) return; const link = document.createElement("a"); link.href = result; link.download = "forma-studio-ai-design.png"; link.click(); }
  return <main className="min-h-screen bg-background"><FormaHeader /><div className="px-5 pt-7"><BackLink /></div><PageIntro eyebrow={eyebrow} title={title} description={description} /><section className="px-5 pb-16"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={upload} /><button type="button" onClick={() => fileRef.current?.click()} className="relative flex min-h-64 w-full items-center justify-center overflow-hidden bg-secondary">{source ? <img src={result ?? source} alt={result ? "AI-designed interior result" : "Uploaded interior"} className={`h-72 w-full object-cover ${busy ? "blur-md" : ""}`} /> : <div className="text-center"><Upload className="mx-auto size-6" /><p className="mt-3 text-sm font-medium">Upload your space</p><p className="mt-1 text-xs text-muted-foreground">JPG, PNG or WEBP</p></div>}{busy && <div className="absolute inset-0 grid place-items-center bg-foreground/25 text-primary-foreground"><LoaderCircle className="animate-spin" /></div>}</button>{source && <div className="mt-5 space-y-4"><div className="flex gap-2 overflow-x-auto pb-1">{suggestions.map((item) => <Button key={item} variant="secondary" size="sm" className="shrink-0 rounded-full" onClick={() => setPrompt(item)}>{item}</Button>)}</div><Textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Describe the changes you want…" className="min-h-28 resize-none" />{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<Button variant="studio" className="h-12 w-full" disabled={busy || prompt.trim().length < 6} onClick={generate}>{busy ? <LoaderCircle className="animate-spin" /> : <Sparkles />}{busy ? "Transforming…" : "Apply AI design"}</Button><div className="grid grid-cols-2 gap-3"><Button variant="outline" onClick={() => { setSource(null); setResult(null); setPrompt(""); }}><RotateCcw />Reset</Button><Button variant="outline" disabled={!result} onClick={download}><Download />Download</Button></div></div>}{!source && <Button variant="outline" className="mt-4 h-11 w-full" onClick={() => fileRef.current?.click()}><ImagePlus />Select a photo</Button>}</section></main>;
}