/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTermsRouteImport } from './routes/_authenticated/terms'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedPhotoToAiRouteImport } from './routes/_authenticated/photo-to-ai'
import { Route as AuthenticatedModelToAiRouteImport } from './routes/_authenticated/model-to-ai'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCloudRouteImport } from './routes/_authenticated/cloud'
import { Route as AuthenticatedAiToVideoRouteImport } from './routes/_authenticated/ai-to-video'
import { Route as AuthenticatedAiEditsRouteImport } from './routes/_authenticated/ai-edits'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTermsRoute = AuthenticatedTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotoToAiRoute = AuthenticatedPhotoToAiRouteImport.update({
  id: '/photo-to-ai',
  path: '/photo-to-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelToAiRoute = AuthenticatedModelToAiRouteImport.update({
  id: '/model-to-ai',
  path: '/model-to-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCloudRoute = AuthenticatedCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiToVideoRoute = AuthenticatedAiToVideoRouteImport.update({
  id: '/ai-to-video',
  path: '/ai-to-video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiEditsRoute = AuthenticatedAiEditsRouteImport.update({
  id: '/ai-edits',
  path: '/ai-edits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai-edits': typeof AuthenticatedAiEditsRoute
  '/ai-to-video': typeof AuthenticatedAiToVideoRoute
  '/cloud': typeof AuthenticatedCloudRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/model-to-ai': typeof AuthenticatedModelToAiRoute
  '/photo-to-ai': typeof AuthenticatedPhotoToAiRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai-edits': typeof AuthenticatedAiEditsRoute
  '/ai-to-video': typeof AuthenticatedAiToVideoRoute
  '/cloud': typeof AuthenticatedCloudRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/model-to-ai': typeof AuthenticatedModelToAiRoute
  '/photo-to-ai': typeof AuthenticatedPhotoToAiRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/terms': typeof AuthenticatedTermsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ai-edits': typeof AuthenticatedAiEditsRoute
  '/_authenticated/ai-to-video': typeof AuthenticatedAiToVideoRoute
  '/_authenticated/cloud': typeof AuthenticatedCloudRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/model-to-ai': typeof AuthenticatedModelToAiRoute
  '/_authenticated/photo-to-ai': typeof AuthenticatedPhotoToAiRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/terms': typeof AuthenticatedTermsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/ai-edits'
    | '/ai-to-video'
    | '/cloud'
    | '/dashboard'
    | '/history'
    | '/model-to-ai'
    | '/photo-to-ai'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/wallet'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/ai-edits'
    | '/ai-to-video'
    | '/cloud'
    | '/dashboard'
    | '/history'
    | '/model-to-ai'
    | '/photo-to-ai'
    | '/privacy'
    | '/studio'
    | '/terms'
    | '/wallet'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/ai-edits'
    | '/_authenticated/ai-to-video'
    | '/_authenticated/cloud'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/model-to-ai'
    | '/_authenticated/photo-to-ai'
    | '/_authenticated/privacy'
    | '/_authenticated/studio'
    | '/_authenticated/terms'
    | '/_authenticated/wallet'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terms': {
      id: '/_authenticated/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthenticatedTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photo-to-ai': {
      id: '/_authenticated/photo-to-ai'
      path: '/photo-to-ai'
      fullPath: '/photo-to-ai'
      preLoaderRoute: typeof AuthenticatedPhotoToAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-to-ai': {
      id: '/_authenticated/model-to-ai'
      path: '/model-to-ai'
      fullPath: '/model-to-ai'
      preLoaderRoute: typeof AuthenticatedModelToAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cloud': {
      id: '/_authenticated/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AuthenticatedCloudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-to-video': {
      id: '/_authenticated/ai-to-video'
      path: '/ai-to-video'
      fullPath: '/ai-to-video'
      preLoaderRoute: typeof AuthenticatedAiToVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-edits': {
      id: '/_authenticated/ai-edits'
      path: '/ai-edits'
      fullPath: '/ai-edits'
      preLoaderRoute: typeof AuthenticatedAiEditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAiEditsRoute: typeof AuthenticatedAiEditsRoute
  AuthenticatedAiToVideoRoute: typeof AuthenticatedAiToVideoRoute
  AuthenticatedCloudRoute: typeof AuthenticatedCloudRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedModelToAiRoute: typeof AuthenticatedModelToAiRoute
  AuthenticatedPhotoToAiRoute: typeof AuthenticatedPhotoToAiRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedTermsRoute: typeof AuthenticatedTermsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAiEditsRoute: AuthenticatedAiEditsRoute,
  AuthenticatedAiToVideoRoute: AuthenticatedAiToVideoRoute,
  AuthenticatedCloudRoute: AuthenticatedCloudRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedModelToAiRoute: AuthenticatedModelToAiRoute,
  AuthenticatedPhotoToAiRoute: AuthenticatedPhotoToAiRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedTermsRoute: AuthenticatedTermsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
