/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ModelToAiRouteImport } from './routes/model-to-ai'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiToVideoRouteImport } from './routes/ai-to-video'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelToAiRoute = ModelToAiRouteImport.update({
  id: '/model-to-ai',
  path: '/model-to-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToVideoRoute = AiToVideoRouteImport.update({
  id: '/ai-to-video',
  path: '/ai-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-to-video': typeof AiToVideoRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/model-to-ai': typeof ModelToAiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-to-video': typeof AiToVideoRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/model-to-ai': typeof ModelToAiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-to-video': typeof AiToVideoRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/model-to-ai': typeof ModelToAiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-to-video'
    | '/auth'
    | '/dashboard'
    | '/model-to-ai'
    | '/sitemap.xml'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-to-video'
    | '/auth'
    | '/dashboard'
    | '/model-to-ai'
    | '/sitemap.xml'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/ai-to-video'
    | '/auth'
    | '/dashboard'
    | '/model-to-ai'
    | '/sitemap.xml'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToVideoRoute: typeof AiToVideoRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ModelToAiRoute: typeof ModelToAiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-to-ai': {
      id: '/model-to-ai'
      path: '/model-to-ai'
      fullPath: '/model-to-ai'
      preLoaderRoute: typeof ModelToAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-to-video': {
      id: '/ai-to-video'
      path: '/ai-to-video'
      fullPath: '/ai-to-video'
      preLoaderRoute: typeof AiToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToVideoRoute: AiToVideoRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ModelToAiRoute: ModelToAiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
