import { Capacitor } from "@capacitor/core";
// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        "x-formai-operation-id": crypto.randomUUID(),
        "x-formai-client": Capacitor.isNativePlatform() && Capacitor.getPlatform() === "ios" ? "ios" : "web",
        ...(localStorage.getItem("formai-ai-consent-openai-v2") === "1" ? { "x-formai-ai-consent": "openai-v2" } : {}),
      },
    })
  },
)
